export const REQUEST_POKEMON = 'REQUEST_POKEMON';
export const RECEIVE_POKEMON = 'RECEIVE_POKEMON';
export const FAILED_POKEMON = 'FAILED_POKEMON';

export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';

export const REQUEST_TYPE = 'REQUEST_TYPE';
export const RECEIVE_TYPE = 'RECEIVE_TYPE';
export const FAILED_TYPE = 'FAILED_TYPE';

export const UPDATE_INFO_PANEL = 'UPDATE_INFO_PANEL';
export const OPEN_INFO_PANEL = 'OPEN_INFO_PANEL';
export const CLOSE_INFO_PANEL = 'CLOSE_INFO_PANEL';