export const REQUEST_POKEMON = 'REQUEST_POKEMON';
export const RECEIVE_POKEMON = 'RECEIVE_POKEMON';
export const FAILED_POKEMON = 'FAILED_POKEMON';
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';